server.port=8090
#server.servlet.context-path=/

spring.freemarker.suffix: .ftlh
spring.freemarker.template-loader-path: classpath:/templates
spring.freemarker.request-context-attribute: rc

spring.mvc.static-path-pattern=/static/**

spring.mvc.favicon.enabled=false