server:
  port: 8090
  servlet:
    context-path: /

logging:
  level:
    root: INFO
    ru.itis.dis403: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg"
  file:
    name: /app/logs/telemetry.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30